services:
  web:
    build: './backend'
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - 8004:8000
    depends_on:
      - redis
  celery:
    build: './backend'
    command: celery -A celery_core.worker worker --loglevel=info
    ports:
      - 5556:5556
    depends_on:
      - web
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"