services:
  backend:
    build: './backend'
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - 8004:8000
    depends_on:
      - redis
  frontend:
    build: './frontend'
    ports:
     - 5173:5173

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data 
  
  volumes:
    pgdata: